### ISSUE TITLE
BUG - Image is published under wrong name

### ISSUE THREAD

**Issue by Finwood** [IRNAS/irnas-docker-software#1]
The CI docker image gets published under the name [vanilla-zephyr-v3.6.0-ci](https://github.com/orgs/IRNAS/packages/container/package/vanilla-zephyr-v3.6.0-ci), while the build scripts assumes [vanilla-zephyr-ci-v3.6.0](https://github.com/IRNAS/irnas-docker-software/blob/04b55c8da4714541b3f9e38bc97cc8ba6cf8da75/vanilla-zephyr/build_ci.sh#L9).

This breaks the development build, because the image vanilla-zephyr-**ci-v3.6.0** is missing from the registry:

https://github.com/IRNAS/irnas-docker-software/blob/04b55c8da4714541b3f9e38bc97cc8ba6cf8da75/vanilla-zephyr/build_dev.sh#L4

**Comment by MarkoSagadin** [comment]
Related to [this](https://github.com/IRNAS/irnas-docker-software/issues/2#issuecomment-2225486367)

The build script were fixed so they use the new naming scheme.
