### ISSUE TITLE
BUG - Development Image missing

### ISSUE THREAD

**Issue by Finwood** [IRNAS/irnas-docker-software#2]
#### Describe the bug

The vanilla-zephyr-dev-v3.6.0 image is missing from the [package registry](https://github.com/orgs/IRNAS/packages). This is required for the docker-based development workflow:

https://github.com/IRNAS/starcopter-demo-template/blob/92c020b2cd616722605a90f9caac35bccdb39525/scripts/enter_docker_container.sh#L13

#### Additional context

On Thursday the image still was present, it must have been removed in the past days.

**Comment by MarkoSagadin** [comment]
I changed the naming so it would make more sense: 
- name of the image: `vanilla-zepyhr`
- version of the Zephyr SDK: `v3.6.0` (in this case)
- additional qualifier: `ci` or `dev`

This is fixed now, so please use the new package.
