### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by KajbaM** [IRNAS/irnas-docker-software#6]
## Context

Currently, only bash is supported in Docker images. This makes me sad. Can we have the fancy zsh stuff please?

## Required steps / Implementation details

Add zsh to docker images.

## Definition of Done

We can use zsh in docker images.

**Comment by MarkoSagadin** [comment]
Can you define what you consider to be "fancy zsh stuff"? Zsh enables tons of customizations, there are several plugin systems that do [that](https://ohmyz.sh/).

Are you referring to my setup?

**Comment by KajbaM** [comment]
I was refering to your setup yes, I know oh my zsh exists yes but for now yeee good enough
